# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sPn3ksg6iTAuOMxx9xm08uvDn0gzA365
"""

"""
Fashion MNIST Classification using CNN (Critical Thinking Assignment)
Following professional and scientific best practices.
Incorporates concepts from: https://www.kaggle.com/code/pavansanagapati/a-simple-cnn-model-beginner-guide
"""

# Import required libraries
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras import datasets, layers, models
from sklearn.metrics import classification_report, confusion_matrix
import seaborn as sns

# 1. Load Fashion MNIST Dataset
(train_images, train_labels), (test_images, test_labels) = datasets.fashion_mnist.load_data()

# 2. Normalize images
train_images = train_images / 255.0
test_images = test_images / 255.0

# 3. Reshape data to fit model input requirements (28x28x1)
train_images = train_images.reshape((train_images.shape[0], 28, 28, 1))
test_images = test_images.reshape((test_images.shape[0], 28, 28, 1))

# 4. Define class names for clarity
class_names = ['T-shirt/top', 'Trouser', 'Pullover', 'Dress', 'Coat',
               'Sandal', 'Shirt', 'Sneaker', 'Bag', 'Ankle boot']

# 5. Build CNN model, best practice: use multiple layers + dropout
model = models.Sequential([
    layers.Conv2D(32, (3, 3), activation='relu', input_shape=(28, 28, 1)),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.Flatten(),
    layers.Dropout(0.5),
    layers.Dense(64, activation='relu'),
    layers.Dense(10, activation='softmax')
])

# 6. Compile the model
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

# 7. Train the model
history = model.fit(train_images, train_labels, epochs=10,
                    validation_split=0.1, batch_size=64)

# 8. Evaluate the model
loss, accuracy = model.evaluate(test_images, test_labels)
print("\nTest Accuracy:", accuracy)

# 9. Generate classification report and confusion matrix
y_pred = np.argmax(model.predict(test_images), axis=-1)
print("\nClassification Report:\n", classification_report(test_labels, y_pred, target_names=class_names))

# 10. Plot confusion matrix
cm = confusion_matrix(test_labels, y_pred)
plt.figure(figsize=(10, 8))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=class_names, yticklabels=class_names)
plt.xlabel('Predicted')
plt.ylabel('True')
plt.title('Confusion Matrix')
plt.tight_layout()
plt.show()

# 11. Visualize prediction vs actual
plt.figure(figsize=(10, 10))
for i in range(25):
    plt.subplot(5, 5, i + 1)
    plt.xticks([])
    plt.yticks([])
    plt.grid(False)
    plt.imshow(test_images[i].reshape(28, 28), cmap=plt.cm.viridis)
    plt.xlabel(f"Prediction: {y_pred[i]}\nActual: {test_labels[i]}")
plt.suptitle('Predictions vs Actual Labels (Sample Output)', fontsize=14)
plt.tight_layout()
plt.show()

# 12. Save final model
model.save("fashion_mnist_cnn_model.h5")